### ISSUE TITLE
Feature request: ESPHome support

### ISSUE THREAD

**Issue by BradleyFord** [Gifford47/HCPBridgeMqtt#9]
I am just working on getting this running on my board; but it would be great if this code could be added into ESPHome!!

**Comment by Gifford47** [comment]
Why do you want ESPHome support when the homeassistant auto-discovery already exists? Are there any advantages of using ESPHome ?

**Comment by BradleyFord** [comment]
From a selfish perspective, so it fits in with how I am using all the other ESPs.

But in terms of practical functionality it would then be very easy to use it as a Bluetooth proxy covering the garage area as the location would be perfect. (centrally located in the room, on the ceiling looking down at everything)

**Comment by jkaberg** [comment]
@Gifford47 since my use case aligns with @BradleyFord I'd like to just get you're 2 cents on how much work we're talking about? As I figure it would need to "support" the [external component](https://esphome.io/components/external_components.html) in Esphome.

Just to bring in another argument as to why; updates and managment. With the [Esphome Dashboard](https://github.com/esphome/dashboard) one can manage all of ones esp32 devices centrally, makes stuff like secrets and updating a lot easier.

**Comment by jmonsted** [comment]
Just wanted to throw a quick "me too!" in here. No big deal, but this is my only device speaking MQTT and as jkaberg noted, it would be easier to manage along with the 15 other esphome devices.

**Comment by Eagle3386** [comment]
October 2024, I'd like to add an upvote too! 😉

**Comment by Gifford47** [comment]
@14yannick already done an awesome job to integrate it on esphome. Look at:
https://github.com/14yannick/esphome-hcpbridge
